"""ORM model exports — ensures Alembic can discover all tables."""
from app.models.base import TimestampMixin  # noqa: F401
from app.models.organization import Organization  # noqa: F401
from app.models.user import User  # noqa: F401
from app.models.role import Role  # noqa: F401
from app.models.permission import Permission  # noqa: F401
from app.models.role_permission import RolePermission  # noqa: F401
from app.models.user_role import UserRole  # noqa: F401
from app.models.audit_log import AuditLog  # noqa: F401
from app.models.plan import Plan  # noqa: F401
from app.models.file_metadata import FileMetadata  # noqa: F401
from app.models.refresh_token import RefreshToken  # noqa: F401
from app.models.simulator_vendor import SimulatorVendor  # noqa: F401
from app.models.simulator_configuration import SimulatorConfiguration  # noqa: F401
from app.models.simulator_session import SimulatorSession  # noqa: F401
from app.models.integration_log import IntegrationLog  # noqa: F401
from app.models.consent import Consent  # noqa: F401
from app.models.vessel import Vessel  # noqa: F401
from app.models.port import Port  # noqa: F401
from app.models.weather_condition import WeatherCondition  # noqa: F401
from app.models.sea_state import SeaState  # noqa: F401
from app.models.visibility_condition import VisibilityCondition  # noqa: F401
from app.models.time_of_day import TimeOfDay  # noqa: F401
from app.models.environment_profile import EnvironmentProfile  # noqa: F401
from app.models.exercise_category import ExerciseCategory  # noqa: F401
from app.models.objective import Objective  # noqa: F401
from app.models.scenario import Scenario  # noqa: F401
from app.models.exercise import Exercise  # noqa: F401
from app.models.exercise_objective import ExerciseObjective  # noqa: F401
from app.models.exercise_variant import ExerciseVariant  # noqa: F401
from app.models.exercise_version import ExerciseVersion  # noqa: F401
from app.models.feature import Feature  # noqa: F401
from app.models.plan_feature import PlanFeature  # noqa: F401
from app.models.plan_exercise import PlanExercise  # noqa: F401
from app.models.plan_simulator import PlanSimulator  # noqa: F401
from app.models.organization_subscription import OrganizationSubscription  # noqa: F401
from app.models.organization_usage import OrganizationUsage  # noqa: F401
from app.models.assessment import Assessment  # noqa: F401
from app.models.assessment_exercise import AssessmentExercise  # noqa: F401
from app.models.assessment_participant import AssessmentParticipant  # noqa: F401
from app.models.assessment_schedule import AssessmentSchedule  # noqa: F401
from app.models.assessment_attempt import AssessmentAttempt  # noqa: F401
from app.models.assessment_result import AssessmentResult  # noqa: F401
from app.models.enquiry import Enquiry, EnquiryNote  # noqa: F401
from app.models.enquiry_consent import EnquiryConsent  # noqa: F401
from app.models.onboarding_request import OnboardingRequest  # noqa: F401
from app.models.candidate import Candidate  # noqa: F401
from app.models.user_invitation import UserInvitation  # noqa: F401
from app.models.organization_assignment import OrganizationAssignment  # noqa: F401
from app.models.platform_settings import PlatformSettings  # noqa: F401
from app.models.assessment_campaign import AssessmentCampaign  # noqa: F401
from app.models.assessment_assignment import AssessmentAssignment  # noqa: F401
from app.models.assignment_activity_log import AssignmentActivityLog  # noqa: F401
from app.models.branding_settings import BrandingSettings  # noqa: F401
from app.models.communication_settings import CommunicationSettings  # noqa: F401
from app.models.notification_settings import NotificationSettings  # noqa: F401
from app.models.invoice_settings import InvoiceSettings  # noqa: F401
from app.models.system_preferences import SystemPreferences  # noqa: F401
from app.models.email_template import EmailTemplate  # noqa: F401
from app.models.portal_settings import PortalSettings  # noqa: F401
