"""create_exercise_builder_tables

Revision ID: f360393c1ccb
Revises: 005
Create Date: 2026-06-11 10:38:03.956848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f360393c1ccb'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_categories',
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_exercise_categories_category_code'), 'exercise_categories', ['category_code'], unique=True)
    op.create_index(op.f('ix_exercise_categories_category_name'), 'exercise_categories', ['category_name'], unique=False)
    op.create_index(op.f('ix_exercise_categories_status'), 'exercise_categories', ['status'], unique=False)
    op.create_table('objectives',
    sa.Column('objective_name', sa.String(length=255), nullable=False),
    sa.Column('objective_code', sa.String(length=50), nullable=False),
    sa.Column('competency_area', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_objectives_competency_area'), 'objectives', ['competency_area'], unique=False)
    op.create_index(op.f('ix_objectives_objective_code'), 'objectives', ['objective_code'], unique=True)
    op.create_index(op.f('ix_objectives_objective_name'), 'objectives', ['objective_name'], unique=False)
    op.create_index(op.f('ix_objectives_status'), 'objectives', ['status'], unique=False)
    op.create_table('scenarios',
    sa.Column('scenario_name', sa.String(length=255), nullable=False),
    sa.Column('scenario_code', sa.String(length=50), nullable=False),
    sa.Column('scenario_type', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_scenarios_difficulty'), 'scenarios', ['difficulty'], unique=False)
    op.create_index(op.f('ix_scenarios_scenario_code'), 'scenarios', ['scenario_code'], unique=True)
    op.create_index(op.f('ix_scenarios_scenario_name'), 'scenarios', ['scenario_name'], unique=False)
    op.create_index(op.f('ix_scenarios_scenario_type'), 'scenarios', ['scenario_type'], unique=False)
    op.create_index(op.f('ix_scenarios_status'), 'scenarios', ['status'], unique=False)
    op.create_table('exercises',
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('exercise_code', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('passing_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='0–100'),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True, comment='Minutes'),
    sa.Column('generation_mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['exercise_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_exercises_category_id'), 'exercises', ['category_id'], unique=False)
    op.create_index(op.f('ix_exercises_difficulty'), 'exercises', ['difficulty'], unique=False)
    op.create_index(op.f('ix_exercises_exercise_code'), 'exercises', ['exercise_code'], unique=True)
    op.create_index(op.f('ix_exercises_exercise_name'), 'exercises', ['exercise_name'], unique=False)
    op.create_index(op.f('ix_exercises_scenario_id'), 'exercises', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_exercises_status'), 'exercises', ['status'], unique=False)
    op.create_table('exercise_objectives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'objective_id', name='uq_exercise_objective')
    )
    op.create_index(op.f('ix_exercise_objectives_exercise_id'), 'exercise_objectives', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_objectives_objective_id'), 'exercise_objectives', ['objective_id'], unique=False)
    op.create_table('exercise_variants',
    sa.Column('variant_name', sa.String(length=255), nullable=False),
    sa.Column('variant_code', sa.String(length=50), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=True),
    sa.Column('environment_profile_id', sa.Integer(), nullable=True),
    sa.Column('primary_vessel_id', sa.Integer(), nullable=True),
    sa.Column('secondary_vessel_id', sa.Integer(), nullable=True),
    sa.Column('tertiary_vessel_id', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('passing_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='0–100'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['environment_profile_id'], ['environment_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_vessel_id'], ['vessels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['secondary_vessel_id'], ['vessels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tertiary_vessel_id'], ['vessels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_exercise_variants_environment_profile_id'), 'exercise_variants', ['environment_profile_id'], unique=False)
    op.create_index(op.f('ix_exercise_variants_exercise_id'), 'exercise_variants', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_variants_port_id'), 'exercise_variants', ['port_id'], unique=False)
    op.create_index(op.f('ix_exercise_variants_primary_vessel_id'), 'exercise_variants', ['primary_vessel_id'], unique=False)
    op.create_index(op.f('ix_exercise_variants_status'), 'exercise_variants', ['status'], unique=False)
    op.create_index(op.f('ix_exercise_variants_variant_code'), 'exercise_variants', ['variant_code'], unique=True)
    op.create_index(op.f('ix_exercise_variants_variant_name'), 'exercise_variants', ['variant_name'], unique=False)
    op.create_table('exercise_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_versions_exercise_id'), 'exercise_versions', ['exercise_id'], unique=False)
    op.alter_column('consent_records', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment='UUID reference — denormalised for easy lookup without join',
               existing_comment='UUID reference — denormalised for easy lookup',
               existing_nullable=True)
    op.alter_column('consent_records', 'policy_version',
               existing_type=sa.VARCHAR(length=50),
               comment="Document version at time of acceptance, e.g. '2026-01-01'",
               existing_comment='Document version at time of acceptance, e.g. 2026-01-01',
               existing_nullable=False)
    op.create_index(op.f('ix_environment_profiles_sea_state_id'), 'environment_profiles', ['sea_state_id'], unique=False)
    op.create_index(op.f('ix_environment_profiles_time_of_day_id'), 'environment_profiles', ['time_of_day_id'], unique=False)
    op.create_index(op.f('ix_environment_profiles_visibility_condition_id'), 'environment_profiles', ['visibility_condition_id'], unique=False)
    op.create_index(op.f('ix_environment_profiles_weather_condition_id'), 'environment_profiles', ['weather_condition_id'], unique=False)
    op.create_index(op.f('ix_file_metadata_organization_id'), 'file_metadata', ['organization_id'], unique=False)
    op.drop_index('ix_integration_logs_created_at', table_name='integration_logs')
    op.drop_index('ix_integration_logs_status', table_name='integration_logs')
    op.drop_index('ix_integration_logs_vendor', table_name='integration_logs')
    op.drop_constraint('integration_logs_simulator_vendor_id_fkey', 'integration_logs', type_='foreignkey')
    op.create_foreign_key(None, 'integration_logs', 'simulator_vendors', ['simulator_vendor_id'], ['id'])
    op.drop_constraint('permissions_name_key', 'permissions', type_='unique')
    op.drop_index('ix_permissions_name', table_name='permissions')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.drop_constraint('plans_slug_key', 'plans', type_='unique')
    op.drop_index('ix_plans_slug', table_name='plans')
    op.create_index(op.f('ix_plans_slug'), 'plans', ['slug'], unique=True)
    op.drop_constraint('ports_port_code_key', 'ports', type_='unique')
    op.drop_index('ix_ports_port_code', table_name='ports')
    op.create_index(op.f('ix_ports_port_code'), 'ports', ['port_code'], unique=True)
    op.create_index(op.f('ix_ports_city'), 'ports', ['city'], unique=False)
    op.create_index(op.f('ix_ports_traffic_density'), 'ports', ['traffic_density'], unique=False)
    op.drop_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', type_='unique')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_constraint('roles_slug_key', 'roles', type_='unique')
    op.drop_index('ix_roles_slug', table_name='roles')
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    op.alter_column('sea_states', 'wave_height_min',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Minimum wave height in metres',
               existing_nullable=True)
    op.alter_column('sea_states', 'wave_height_max',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Maximum wave height in metres',
               existing_nullable=True)
    op.drop_constraint('sea_states_name_key', 'sea_states', type_='unique')
    op.drop_index('ix_sea_states_name', table_name='sea_states')
    op.create_index(op.f('ix_sea_states_name'), 'sea_states', ['name'], unique=True)
    op.drop_index('ix_simulator_configurations_vendor', table_name='simulator_configurations')
    op.drop_constraint('simulator_configurations_simulator_vendor_id_fkey', 'simulator_configurations', type_='foreignkey')
    op.create_foreign_key(None, 'simulator_configurations', 'simulator_vendors', ['simulator_vendor_id'], ['id'])
    op.drop_index('ix_simulator_sessions_reference', table_name='simulator_sessions')
    op.drop_index('ix_simulator_sessions_start_time', table_name='simulator_sessions')
    op.drop_index('ix_simulator_sessions_status', table_name='simulator_sessions')
    op.create_index(op.f('ix_simulator_sessions_session_reference'), 'simulator_sessions', ['session_reference'], unique=False)
    op.drop_constraint('simulator_sessions_simulator_vendor_id_fkey', 'simulator_sessions', type_='foreignkey')
    op.drop_constraint('simulator_sessions_organization_id_fkey', 'simulator_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'simulator_sessions', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'simulator_sessions', 'simulator_vendors', ['simulator_vendor_id'], ['id'])
    op.drop_index('ix_simulator_vendors_code', table_name='simulator_vendors')
    op.drop_index('ix_simulator_vendors_status', table_name='simulator_vendors')
    op.drop_constraint('time_of_day_name_key', 'time_of_day', type_='unique')
    op.drop_index('ix_time_of_day_name', table_name='time_of_day')
    op.create_index(op.f('ix_time_of_day_name'), 'time_of_day', ['name'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('users_organization_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.alter_column('vessels', 'length',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Length in metres',
               existing_nullable=True)
    op.alter_column('vessels', 'beam',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Beam in metres',
               existing_nullable=True)
    op.alter_column('vessels', 'draft',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Draft in metres',
               existing_nullable=True)
    op.alter_column('vessels', 'max_speed',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Max speed in knots',
               existing_nullable=True)
    op.drop_constraint('vessels_vessel_code_key', 'vessels', type_='unique')
    op.drop_index('ix_vessels_vessel_code', table_name='vessels')
    op.create_index(op.f('ix_vessels_vessel_code'), 'vessels', ['vessel_code'], unique=True)
    op.alter_column('visibility_conditions', 'visibility_distance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Distance in nautical miles',
               existing_nullable=True)
    op.drop_constraint('visibility_conditions_name_key', 'visibility_conditions', type_='unique')
    op.drop_index('ix_visibility_conditions_name', table_name='visibility_conditions')
    op.create_index(op.f('ix_visibility_conditions_name'), 'visibility_conditions', ['name'], unique=True)
    op.alter_column('weather_conditions', 'wind_speed',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Wind speed in knots',
               existing_nullable=True)
    op.alter_column('weather_conditions', 'visibility_range',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Visibility range in nautical miles',
               existing_nullable=True)
    op.drop_constraint('weather_conditions_name_key', 'weather_conditions', type_='unique')
    op.drop_index('ix_weather_conditions_name', table_name='weather_conditions')
    op.create_index(op.f('ix_weather_conditions_name'), 'weather_conditions', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_conditions_name'), table_name='weather_conditions')
    op.create_index('ix_weather_conditions_name', 'weather_conditions', ['name'], unique=False)
    op.create_unique_constraint('weather_conditions_name_key', 'weather_conditions', ['name'])
    op.alter_column('weather_conditions', 'visibility_range',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Visibility range in nautical miles',
               existing_nullable=True)
    op.alter_column('weather_conditions', 'wind_speed',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Wind speed in knots',
               existing_nullable=True)
    op.drop_index(op.f('ix_visibility_conditions_name'), table_name='visibility_conditions')
    op.create_index('ix_visibility_conditions_name', 'visibility_conditions', ['name'], unique=False)
    op.create_unique_constraint('visibility_conditions_name_key', 'visibility_conditions', ['name'])
    op.alter_column('visibility_conditions', 'visibility_distance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Distance in nautical miles',
               existing_nullable=True)
    op.drop_index(op.f('ix_vessels_vessel_code'), table_name='vessels')
    op.create_index('ix_vessels_vessel_code', 'vessels', ['vessel_code'], unique=False)
    op.create_unique_constraint('vessels_vessel_code_key', 'vessels', ['vessel_code'])
    op.alter_column('vessels', 'max_speed',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Max speed in knots',
               existing_nullable=True)
    op.alter_column('vessels', 'draft',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Draft in metres',
               existing_nullable=True)
    op.alter_column('vessels', 'beam',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Beam in metres',
               existing_nullable=True)
    op.alter_column('vessels', 'length',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Length in metres',
               existing_nullable=True)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_organization_id_fkey', 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_time_of_day_name'), table_name='time_of_day')
    op.create_index('ix_time_of_day_name', 'time_of_day', ['name'], unique=False)
    op.create_unique_constraint('time_of_day_name_key', 'time_of_day', ['name'])
    op.create_index('ix_simulator_vendors_status', 'simulator_vendors', ['status'], unique=False)
    op.create_index('ix_simulator_vendors_code', 'simulator_vendors', ['code'], unique=False)
    op.drop_constraint(None, 'simulator_sessions', type_='foreignkey')
    op.drop_constraint(None, 'simulator_sessions', type_='foreignkey')
    op.create_foreign_key('simulator_sessions_organization_id_fkey', 'simulator_sessions', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('simulator_sessions_simulator_vendor_id_fkey', 'simulator_sessions', 'simulator_vendors', ['simulator_vendor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_simulator_sessions_session_reference'), table_name='simulator_sessions')
    op.create_index('ix_simulator_sessions_status', 'simulator_sessions', ['status'], unique=False)
    op.create_index('ix_simulator_sessions_start_time', 'simulator_sessions', ['start_time'], unique=False)
    op.create_index('ix_simulator_sessions_reference', 'simulator_sessions', ['session_reference'], unique=False)
    op.drop_constraint(None, 'simulator_configurations', type_='foreignkey')
    op.create_foreign_key('simulator_configurations_simulator_vendor_id_fkey', 'simulator_configurations', 'simulator_vendors', ['simulator_vendor_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_simulator_configurations_vendor', 'simulator_configurations', ['simulator_vendor_id'], unique=False)
    op.drop_index(op.f('ix_sea_states_name'), table_name='sea_states')
    op.create_index('ix_sea_states_name', 'sea_states', ['name'], unique=False)
    op.create_unique_constraint('sea_states_name_key', 'sea_states', ['name'])
    op.alter_column('sea_states', 'wave_height_max',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Maximum wave height in metres',
               existing_nullable=True)
    op.alter_column('sea_states', 'wave_height_min',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Minimum wave height in metres',
               existing_nullable=True)
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.create_index('ix_roles_slug', 'roles', ['slug'], unique=False)
    op.create_unique_constraint('roles_slug_key', 'roles', ['slug'])
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', ['token_hash'])
    op.drop_index(op.f('ix_ports_traffic_density'), table_name='ports')
    op.drop_index(op.f('ix_ports_city'), table_name='ports')
    op.drop_index(op.f('ix_ports_port_code'), table_name='ports')
    op.create_index('ix_ports_port_code', 'ports', ['port_code'], unique=False)
    op.create_unique_constraint('ports_port_code_key', 'ports', ['port_code'])
    op.drop_index(op.f('ix_plans_slug'), table_name='plans')
    op.create_index('ix_plans_slug', 'plans', ['slug'], unique=False)
    op.create_unique_constraint('plans_slug_key', 'plans', ['slug'])
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_index('ix_permissions_name', 'permissions', ['name'], unique=False)
    op.create_unique_constraint('permissions_name_key', 'permissions', ['name'])
    op.drop_constraint(None, 'integration_logs', type_='foreignkey')
    op.create_foreign_key('integration_logs_simulator_vendor_id_fkey', 'integration_logs', 'simulator_vendors', ['simulator_vendor_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_integration_logs_vendor', 'integration_logs', ['simulator_vendor_id'], unique=False)
    op.create_index('ix_integration_logs_status', 'integration_logs', ['status'], unique=False)
    op.create_index('ix_integration_logs_created_at', 'integration_logs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_file_metadata_organization_id'), table_name='file_metadata')
    op.drop_index(op.f('ix_environment_profiles_weather_condition_id'), table_name='environment_profiles')
    op.drop_index(op.f('ix_environment_profiles_visibility_condition_id'), table_name='environment_profiles')
    op.drop_index(op.f('ix_environment_profiles_time_of_day_id'), table_name='environment_profiles')
    op.drop_index(op.f('ix_environment_profiles_sea_state_id'), table_name='environment_profiles')
    op.alter_column('consent_records', 'policy_version',
               existing_type=sa.VARCHAR(length=50),
               comment='Document version at time of acceptance, e.g. 2026-01-01',
               existing_comment="Document version at time of acceptance, e.g. '2026-01-01'",
               existing_nullable=False)
    op.alter_column('consent_records', 'user_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment='UUID reference — denormalised for easy lookup',
               existing_comment='UUID reference — denormalised for easy lookup without join',
               existing_nullable=True)
    op.drop_index(op.f('ix_exercise_versions_exercise_id'), table_name='exercise_versions')
    op.drop_table('exercise_versions')
    op.drop_index(op.f('ix_exercise_variants_variant_name'), table_name='exercise_variants')
    op.drop_index(op.f('ix_exercise_variants_variant_code'), table_name='exercise_variants')
    op.drop_index(op.f('ix_exercise_variants_status'), table_name='exercise_variants')
    op.drop_index(op.f('ix_exercise_variants_primary_vessel_id'), table_name='exercise_variants')
    op.drop_index(op.f('ix_exercise_variants_port_id'), table_name='exercise_variants')
    op.drop_index(op.f('ix_exercise_variants_exercise_id'), table_name='exercise_variants')
    op.drop_index(op.f('ix_exercise_variants_environment_profile_id'), table_name='exercise_variants')
    op.drop_table('exercise_variants')
    op.drop_index(op.f('ix_exercise_objectives_objective_id'), table_name='exercise_objectives')
    op.drop_index(op.f('ix_exercise_objectives_exercise_id'), table_name='exercise_objectives')
    op.drop_table('exercise_objectives')
    op.drop_index(op.f('ix_exercises_status'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_scenario_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_exercise_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_exercise_code'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_difficulty'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_category_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_scenarios_status'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_scenario_type'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_scenario_name'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_scenario_code'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_difficulty'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_objectives_status'), table_name='objectives')
    op.drop_index(op.f('ix_objectives_objective_name'), table_name='objectives')
    op.drop_index(op.f('ix_objectives_objective_code'), table_name='objectives')
    op.drop_index(op.f('ix_objectives_competency_area'), table_name='objectives')
    op.drop_table('objectives')
    op.drop_index(op.f('ix_exercise_categories_status'), table_name='exercise_categories')
    op.drop_index(op.f('ix_exercise_categories_category_name'), table_name='exercise_categories')
    op.drop_index(op.f('ix_exercise_categories_category_code'), table_name='exercise_categories')
    op.drop_table('exercise_categories')
    # ### end Alembic commands ###
